# 1. Vector Spaces

# Matrix-Vector Dot Product

Write a Python function that computes the dot product of a matrix and a vector. The function should return a list representing the resulting vector if the operation is valid, or -1 if the matrix and vector dimensions are incompatible. A matrix (a list of lists) can be dotted with a vector (a list) only if the number of columns in the matrix equals the length of the vector. For example, an n x m matrix requires a vector of length m.

In [2]:
def matrix_dot_vector(a: list[list[int|float]], b: list[int|float]) -> list[int|float]:
	# Return a list where each element is the dot product of a row of 'a' with 'b'.
	# If the number of columns in 'a' does not match the length of 'b', return -1.
        if not a or not b:
            return -1
        
        rows = len(a)
        cols = len(a[0])

        if cols != len(b):
              return -1
        
        result = []

        for i in range(rows):
              dot_product = 0
              for j in range(cols):
                    dot_product += a[i][j] * b[j]

              result.append(dot_product)

        return result



# Transpose of a Matrix

Write a Python function that computes the transpose of a given 2D matrix. The transpose of a matrix is formed by turning its rows into columns and columns into rows. For an m×n matrix, the transpose will be an n×m matrix.

a[i][j]  →  result[j][i]

In [ ]:
def transpose_matrix(a: list[list[int|float]]) -> list[list[int|float]]:
    """
    Transpose a 2D matrix by swapping rows and columns.
    
    Args:
        a: A 2D matrix of shape (m, n)
    
    Returns:
        The transposed matrix of shape (n, m)
    """
    # Your code here
    rows = len(a)
    cols = len(a[0])

    result = [[0 for _ in range(rows)] for _ in range(cols)]

    for i in range(rows):
        for j in range(cols):
            result[j][i] = a[i][j]

    return result


# Convert Vector to Diagonal Matrix

Write a Python function to convert a 1D numpy array into a diagonal matrix. The function should take in a 1D numpy array x and return a 2D numpy array representing the diagonal matrix.

matrix[i][i] = x[i]

In [5]:
import numpy as np

def make_diagonal(x):
	# Your code here
	
    n = len(x)
    result = np.zeros((n, n))

    for i in range(n):
        result[i][i] = x[i]

    return result


x = np.array([4,7,9])

print(make_diagonal(x))

[[4. 0. 0.]
 [0. 7. 0.]
 [0. 0. 9.]]


In [6]:
import numpy as np

def make_diagonal(x):
	# Your code here
	return np.diag(x)

# Dot Product Calculator

Write a Python function to calculate the dot product of two vectors. The function should take two 1D NumPy arrays as input and return the dot product as a single number.

In [1]:
import numpy as np

def calculate_dot_product(vec1, vec2):
	"""
	Calculate the dot product of two vectors.
	Args:
		vec1 (numpy.ndarray): 1D array representing the first vector.
		vec2 (numpy.ndarray): 1D array representing the second vector.
	Returns:
		The dot product of the two vectors.
	"""
	# Your code here
	if len(vec1) != len(vec2):
		return -1

	result = 0
	for i in range(len(vec1)):
		result += vec1[i] * vec2[i]
	
	return result

# Scalar Multiplication of a Matrix

Write a Python function that multiplies a matrix by a scalar and returns the result.

In [2]:
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	
	rows = len(matrix)
	cols = len(matrix[0])

	result = [[0 for _ in range(cols)] for _ in range(rows)]

	for i in range(rows):
		for j in range(cols):
			result[i][j] = matrix[i][j] * scalar

	return result

# Find the column space of a matrix
Medium
Linear Algebra

Task: Compute the Column Space of a Matrix
In this task, you are required to implement a function matrix_image(A) that calculates the column space of a given matrix A. The column space, also known as the image or span, consists of all linear combinations of the columns of A. To find this, you'll use concepts from linear algebra, focusing on identifying independent columns that span the matrix's image. Your task: Implement the function matrix_image(A) to return the basis vectors that span the column space of A. These vectors should be extracted from the original matrix and correspond to the independent columns.

In [ ]:

import numpy as np

def matrix_image(A):
	# Write your code here
	A = np.array(A)

	# Q = Othrogonal Vectors
	# R = Triangular Matrix
	Q, R = np.linalg.qr(A)

	# Rank of matrix
	rank = np.linalg.matrix_rank(A)

	# Pivot columns indices
	pivots = np.where(np.abs(np.diag(R)) > 1e-10)[0]

	#Independent columns from original matrix
	return A[:, pivots]


# Calculate Cosine Similarity Between Vectors

Task: Implement Cosine Similarity
In this task, you need to implement a function cosine_similarity(v1, v2) that calculates the cosine similarity between two vectors. Cosine similarity measures the cosine of the angle between two vectors, indicating their directional similarity.

Input:

v1 and v2: Numpy arrays representing the input vectors.
Output:

A float representing the cosine similarity.

Constraints:

Both input vectors must have the same shape.
Input vectors cannot be empty or have zero magnitude.

cosine_similarity = dot / (magA * magB)

In [3]:
import numpy as np

def cosine_similarity(v1, v2):
	"""
	Calculate the cosine_similarity of two vectors.
	Args:
		vec1 (numpy.ndarray): 1D array representing the first vector.
		vec2 (numpy.ndarray): 1D array representing the second vector.
	Returns:
		The cosine_similarity of the two vectors.
	"""
	# Implement your code here
	if v1.shape != v2.shape:
		return -1

	if v1.size == 0:
		return -1

	dot = 0
	for i in range(len(v1)):
		dot += v1[i] * v2[i]

	mag1 = 0
	mag2 = 0

	for i in range(len(v1)):
		mag1 += v1[i]**2
		mag2 += v2[i]**2

	mag1 = mag1 ** 0.5
	mag2 = mag2 ** 0.5

	if mag1 == 0 or mag2 == 0:
		return -1

	return dot/(mag1*mag2)

	

In [ ]:
import numpy as np

def cs(v1, v2):
    if v1.shape != v2.shape:
        return -1
    if np.linalg.norm(v1) == 0 or np.linalg.norm(v2) == 0:
        return -1
    return np.dot(v1 ,v2) / (np.linalg.norm(v1) * np.linalg.norm(v2))



# 2. Matric Operations

# Reshape Matrix

Write a Python function that reshapes a given matrix into a specified shape. if it cant be reshaped return back an empty list []

In [1]:
import numpy as np

def reshape_matrix(a: list[list[int|float]], new_shape: tuple[int, int]) -> list[list[int|float]]:
	#Write your code here and return a python list after reshaping by using numpy's tolist() method
	arr = np.array(a)

	if arr.size != new_shape[0] * new_shape[1]:
		return []
	
	reshaped_matrix = arr.reshape(new_shape)

	return reshaped_matrix.tolist()

# Scalar Multiplication of a Matrix

Write a Python function that multiplies a matrix by a scalar and returns the result.

In [ ]:
def scalar_multiply(matrix: list[list[int|float]], scalar: int|float) -> list[list[int|float]]:
	
	rows = len(matrix)
	cols = len(matrix[0])

	result = [[0 for _ in range(cols)] for _ in range(rows)]

	for i in range(rows):
		for j in range(cols):
			result[i][j] = matrix[i][j] * scalar

	return result

# Implement Compressed Row Sparse Matrix (CSR) Format Conversion

Task: Convert a Dense Matrix to Compressed Row Sparse (CSR) Format
Your task is to implement a function that converts a given dense matrix into the Compressed Row Sparse (CSR) format, an efficient storage representation for sparse matrices. The CSR format only stores non-zero elements and their positions, significantly reducing memory usage for matrices with a large number of zeros.

Write a function compressed_row_sparse_matrix(dense_matrix) that takes a 2D list dense_matrix as input and returns a tuple containing three lists:

Values array: List of all non-zero elements in row-major order.
Column indices array: Column index for each non-zero element in the values array.
Row pointer array: Cumulative number of non-zero elements per row, indicating the start of each row in the values array.

In [2]:
def compressed_row_sparse_matrix(dense_matrix):

    values = []
    col_index = []
    row_ptr = [0]

    for row in dense_matrix:
        for j, val in enumerate(row):

            if val != 0:
                values.append(val)
                col_index.append(j)

        row_ptr.append(len(values))

    return (values, col_index, row_ptr)

# Implement Orthogonal Projection of a Vector onto a Line

Task: Compute the Orthogonal Projection of a Vector
Your task is to implement a function that calculates the orthogonal projection of a vector v onto another vector L. This projection results in the vector on L that is closest to v.

Write a function orthogonal_projection(v, L) that takes in two lists, v (the vector to be projected) and L (the line vector), and returns the orthogonal projection of v onto L. The function should output a list representing the projection vector rounded to three decimal places.

In [ ]:

def orthogonal_projection(v, L):
	"""
	Compute the orthogonal projection of vector v onto line L.

	:param v: The vector to be projected
	:param L: The line vector defining the direction of projection
	:return: List representing the projection of v onto L
	"""
	dot_vL = sum(a*b for a,b in zip(v, L))

	dot_LL = sum(a*b for a, b in zip(L, L))

	scalar = dot_vL / dot_LL

	projection = [round(scalar * x, 3) for x in L]

	return projection


# Implement Compressed Column Sparse Matrix Format (CSC)

Task: Create a Compressed Column Sparse Matrix Representation
Your task is to implement a function that converts a dense matrix into its Compressed Column Sparse (CSC) representation. The CSC format stores only non-zero elements of the matrix and is efficient for matrices with a high number of zero elements.

Write a function compressed_col_sparse_matrix(dense_matrix) that takes in a two-dimensional list dense_matrix and returns a tuple of three lists:

values: List of non-zero elements, stored in column-major order.
row indices: List of row indices corresponding to each value in the values array.
column pointer: List that indicates the starting index of each column in the values array.

In [ ]:
def compressed_col_sparse_matrix(dense_matrix):
	"""
	Convert a dense matrix into its Compressed Column Sparse (CSC) representation.

	:param dense_matrix: List of lists representing the dense matrix
	:return: Tuple of (values, row indices, column pointer)
	"""
	if not dense_matrix or not dense_matrix[0]:
		return ([],[],[])

	rows  = len(dense_matrix)
	cols = len(dense_matrix[0])

	values = []
	row_index = []
	col_ptr = [0]

	# Travese col wise
	for j in range(cols):
		for i in range(rows):
			val = dense_matrix[i][j]

			if val != 0:
				values.append(val)
				row_index.append(i)

		col_ptr.append(len(values))

	return (values, row_index, col_ptr)
